using System.Text;
using System.Text.RegularExpressions;

namespace SwBridge.Tools.Macro;

/// <summary>
/// Writes a SWBasic (.swb) macro file to the macros directory.
/// The LLM provides the VBA code as a string and this tool validates,
/// wraps it in the required header, and persists it to disk ready for
/// execution via run_macro.
///
/// <para>
/// Every written macro is enforced to follow the standard convention:
/// <list type="bullet">
///   <item>A structured metadata header using @tag comment lines.</item>
///   <item>A single module — .swb files do not support multiple modules,
///         classes, or user forms.</item>
///   <item>A parameterless <c>Sub main()</c> as the entry point, which
///         is the procedure run_macro will invoke via RunMacro2.</item>
///   <item>An <c>On Error GoTo</c> handler inside <c>main</c> so that
///         runtime failures surface as readable error messages rather
///         than silent SOLIDWORKS dialogs.</item>
/// </list>
/// </para>
/// </summary>
/// <remarks>
/// The LLM must supply the VBA body only — the header is generated by
/// this tool from the provided metadata parameters. If the body already
/// contains a Sub main() declaration, WriteMacroTool will use it as-is
/// rather than wrapping it again.
///
/// Existing files are overwritten without prompting. The LLM should call
/// list_macros first if it wants to check whether a file already exists.
/// </remarks>
public sealed class WriteMacroTool : ISwTool
{
    /// <summary>
    /// Filename characters that SOLIDWORKS and Windows prohibit or that
    /// would cause confusion in the macros directory listing.
    /// </summary>
    private static readonly char[] InvalidFilenameChars =
        Path.GetInvalidFileNameChars();

    /// <summary>
    /// Matches a Sub main() declaration with optional whitespace variants,
    /// used to detect whether the LLM already included the entry point.
    /// </summary>
    private static readonly Regex SubMainPattern = new(
        @"^\s*Sub\s+main\s*\(\s*\)",
        RegexOptions.Multiline | RegexOptions.IgnoreCase | RegexOptions.Compiled);

    /// <summary>
    /// Matches any Class or UserForm module header that would make a .swb
    /// file invalid — .swb supports only a single code module.
    /// </summary>
    private static readonly Regex InvalidModulePattern = new(
        @"^\s*(BEGIN\s+\{|VERSION\s+\d+|Attribute\s+VB_Name)",
        RegexOptions.Multiline | RegexOptions.IgnoreCase | RegexOptions.Compiled);

    private readonly string _macrosDirectory;

    static WriteMacroTool()
    {
        // .NET 5+ only includes UTF and ASCII encodings by default.
        // Windows-1252 (ANSI) is required for SOLIDWORKS .swb compatibility —
        // SW's VBA engine treats the UTF-8 BOM as literal characters, causing
        // a parse error before Sub main() is reached.
        Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
    }

    /// <summary>
    /// Initializes the tool with the path to the macros directory.
    /// </summary>
    /// <param name="macrosDirectory">
    /// Absolute path to the folder where .swb macro files will be written.
    /// The directory is created if it does not exist.
    /// </param>
    public WriteMacroTool(string macrosDirectory)
    {
        _macrosDirectory = macrosDirectory;
    }

    /// <inheritdoc/>
    public string Name => "write_macro";

    /// <inheritdoc/>
    public string Description =>
        "Writes a SWBasic VBA macro (.swb) to the macros directory. " +
        "The macro can then be executed with run_macro. " +
        "Parameters: " +
        "  'filename'    (required) — output filename, e.g. 'create_bracket.swb'. " +
        "  'macro_name'  (required) — human-readable name, e.g. 'Create Mounting Bracket'. " +
        "  'description' (required) — what the macro does and any preconditions. " +
        "  'code'        (required) — the full VBA macro body. Must contain Sub main() " +
        "                             as the entry point. Must not contain class modules " +
        "                             or user forms. Should include On Error GoTo handling. " +
        "                             The standard header is generated automatically. " +
        "Returns 'SUCCESS: <filename>' on success or an 'ERROR:' message if validation fails.";

    /// <inheritdoc/>
    public async Task<string> ExecuteAsync(
        IReadOnlyDictionary<string, string> parameters,
        CancellationToken cancellationToken = default)
    {
        // ---------------------------------------------------------------- //
        //  Extract and validate parameters
        // ---------------------------------------------------------------- //

        if (!parameters.TryGetValue("filename", out var filename) ||
            string.IsNullOrWhiteSpace(filename))
            return "ERROR: Missing required parameter 'filename'.";

        if (!parameters.TryGetValue("macro_name", out var macroName) ||
            string.IsNullOrWhiteSpace(macroName))
            return "ERROR: Missing required parameter 'macro_name'.";

        if (!parameters.TryGetValue("description", out var description) ||
            string.IsNullOrWhiteSpace(description))
            return "ERROR: Missing required parameter 'description'.";

        if (!parameters.TryGetValue("code", out var code) ||
            string.IsNullOrWhiteSpace(code))
            return "ERROR: Missing required parameter 'code'.";

        // ---------------------------------------------------------------- //
        //  Sanitize filename
        // ---------------------------------------------------------------- //

        filename = filename.Trim();

        if (filename.IndexOfAny(InvalidFilenameChars) >= 0 || filename.Contains(".."))
            return "ERROR: Invalid filename. Use only alphanumeric characters, " +
                   "underscores, and hyphens, e.g. 'create_bracket.swb'.";

        if (!filename.EndsWith(".swb", StringComparison.OrdinalIgnoreCase))
            filename += ".swb";

        var fullPath = Path.GetFullPath(Path.Combine(_macrosDirectory, filename));

        var t1 = Path.GetFullPath(_macrosDirectory);

        if (!fullPath.StartsWith(
                Path.GetFullPath(_macrosDirectory),
                StringComparison.OrdinalIgnoreCase))
            return "ERROR: Resolved path is outside the macros directory.";

        // ---------------------------------------------------------------- //
        //  Validate VBA code structure
        // ---------------------------------------------------------------- //

        if (!SubMainPattern.IsMatch(code))
            return "ERROR: The code must contain 'Sub main()' as the entry point. " +
                   "run_macro always invokes the procedure named 'main' in 'MainModule'.";

        if (InvalidModulePattern.IsMatch(code))
            return "ERROR: The code contains class module or UserForm markers. " +
                   ".swb macros support only a single plain code module. " +
                   "Remove any class or form definitions.";

        // ---------------------------------------------------------------- //
        //  Warn if no error handler is present (non-blocking)
        // ---------------------------------------------------------------- //

        var errorHandlerWarning = string.Empty;
        if (!code.Contains("On Error GoTo", StringComparison.OrdinalIgnoreCase))
            errorHandlerWarning =
                "\nWARNING: No 'On Error GoTo' handler found. Runtime errors will " +
                "surface as SOLIDWORKS dialogs rather than text returned to the LLM. " +
                "Consider rewriting with error handling.";

        // ---------------------------------------------------------------- //
        //  Build the complete .swb file content
        // ---------------------------------------------------------------- //

        var content = BuildMacroContent(macroName, description, code);

        // ---------------------------------------------------------------- //
        //  Write to disk
        // ---------------------------------------------------------------- //

        try
        {
            Directory.CreateDirectory(_macrosDirectory);

            await File.WriteAllTextAsync(
                fullPath,
                content,
                Encoding.GetEncoding(1252),
                cancellationToken);

            return $"SUCCESS: Macro written to '{filename}'.{errorHandlerWarning}";
        }
        catch (IOException ex)
        {
            return $"ERROR: Could not write '{filename}' — {ex.Message}.";
        }
        catch (UnauthorizedAccessException ex)
        {
            return $"ERROR: Access denied writing '{filename}' — {ex.Message}.";
        }
    }

    /// <summary>
    /// Assembles the complete .swb file content from the metadata and VBA
    /// body. The generated header uses the @tag convention read by
    /// <see cref="ListMacrosTool"/> so that metadata survives round-trips
    /// through the macros directory.
    /// </summary>
    /// <param name="macroName">Human-readable name for the @name tag.</param>
    /// <param name="description">Description text for the @description tag.</param>
    /// <param name="code">
    /// The VBA body supplied by the LLM. Written as-is after the header,
    /// separated by a blank line.
    /// </param>
    /// <returns>The full UTF-8 string to write to the .swb file.</returns>
    private static string BuildMacroContent(
        string macroName,
        string description,
        string code)
    {
        var sb = new StringBuilder();

        // ---- Metadata header ------------------------------------------- //
        sb.AppendLine($"' @name        {macroName}");

        // Word-wrap long descriptions at 72 characters so the file stays
        // readable in any editor without horizontal scrolling.
        var descriptionLines = WordWrap(description, maxWidth: 72);
        for (var i = 0; i < descriptionLines.Count; i++)
        {
            // First line uses the @description tag; continuation lines are
            // plain comment continuations that ListMacrosTool appends.
            sb.AppendLine(i == 0
                ? $"' @description {descriptionLines[i]}"
                : $"'              {descriptionLines[i]}");
        }

        sb.AppendLine($"' @author      nodestar");
        sb.AppendLine($"' @created     {DateTime.UtcNow:yyyy-MM-dd}");
        sb.AppendLine("'");

        // ---- VBA body --------------------------------------------------- //
        sb.AppendLine(code.TrimEnd());

        return sb.ToString();
    }

    /// <summary>
    /// Splits a string into lines of at most <paramref name="maxWidth"/>
    /// characters, breaking on whitespace where possible.
    /// </summary>
    /// <param name="text">The text to wrap.</param>
    /// <param name="maxWidth">Maximum characters per line.</param>
    /// <returns>List of wrapped lines, never empty.</returns>
    private static List<string> WordWrap(string text, int maxWidth)
    {
        var lines = new List<string>();
        var words = text.Split(' ', StringSplitOptions.RemoveEmptyEntries);
        var current = new StringBuilder();

        foreach (var word in words)
        {
            if (current.Length > 0 &&
                current.Length + 1 + word.Length > maxWidth)
            {
                lines.Add(current.ToString());
                current.Clear();
            }

            if (current.Length > 0)
                current.Append(' ');

            current.Append(word);
        }

        if (current.Length > 0)
            lines.Add(current.ToString());

        if (lines.Count == 0)
            lines.Add(string.Empty);

        return lines;
    }
}
